[package]
name = "client"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
msg_header = { path="../msg_header" }
echo_start = { path="../echo_start" }
echo_complete = { path="../echo_complete" }
echo_req = { path="../echo_req" }
echo_reply = { path="../echo_reply" }
sm = { path="../sm" }

[dev-dependencies]
msg1 = { path="../msg1" }
#msg2 = { path="../msg2" }
