[package]
name = "con_mgr_query_protocol"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
actor = { version = "0.1.0", path = "../../actor" }
an_id = { version = "0.1.0", path = "../../an_id" }
msg_header = { path = "../../msg_header" }
msg_local_macro = { path = "../../msg_local_macro" }
#msg_serde_json = { path = "../../msg_serde_json" }
serde = { version = "1.0.154", features = ["derive"] }
serde_json = "1.0.94"
uuid = { version = "1.3.0", features = ["serde"] }
chrono = "0.4.23"
protocol_set = { version = "0.1.0", path = "../../protocol_set" }
protocol = { version = "0.1.0", path = "../../protocol" }
once_cell = "1.17.1"
actor_bi_dir_channel = { version = "0.1.0", path = "../../actor_bi_dir_channel" }
crossbeam-channel = "0.5.7"

[dev-dependencies]
protocol = { version = "0.1.0", path = "../../protocol" }
echo_requestee_protocol = { version = "0.1.0", path = "../echo_requestee_protocol" }
