[package]
name = "exper_inter_process_channel"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
manager = { path="manager" }
actor = { path="actor" }
actor_executor = { path="actor_executor" }
actor_bi_dir_channel = { path="actor_bi_dir_channel" }
connection_mgr = { path="connection_mgr" }
protocol_set = { path="protocol_set" }
protocol = { path="protocol" }
echo_start_complete_protocol = { path="echo_start_complete_protocol" }
echo_requester_protocol = { path="echo_requester_protocol" }
echo_requestee_protocol = { path="echo_requestee_protocol" }
echo_start = { path="msgs/echo_start" }
echo_complete = { path="msgs/echo_complete" }
echo_req = { path="msgs/echo_req" }
echo_reply = { path="msgs/echo_reply" }
msg_header = { path="msg_header" }
msg_serde_json = { path="msg_serde_json" }
msg1 = { path="msgs/msg1" }
msg2 = { path="msgs/msg2" }
cmd_done = { path="msgs/cmd_done" }
req_their_bi_dir_channel = { path="msgs/req_their_bi_dir_channel" }
rsp_their_bi_dir_channel = { path="msgs/rsp_their_bi_dir_channel" }
req_add_actor = { path="msgs/req_add_actor" }
rsp_add_actor = { path="msgs/rsp_add_actor" }
name_id = { path="name_id" }
client = { path="client" }
server = { path="server" }
uuid = "1.2.2"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
custom_logger = { git = "https://github.com/winksaville/custom_logger", version = "0.2.0" }
crossbeam-channel = "0.5.6"

[workspace]
members = [
    "manager",
    "actor",
    "actor_executor",
    "actor_bi_dir_channel",
    "connection_mgr",
    "protocol_set",
    "protocol",
    "msg_header",
    "msg_serde_json",
    "msgs/msg1",
    "msgs/msg2",
    "msgs/cmd_done",
    "msgs/req_their_bi_dir_channel",
    "msgs/rsp_their_bi_dir_channel",
    "msgs/req_add_actor",
    "msgs/rsp_add_actor",
    "msgs/echo_complete",
    "msgs/echo_reply",
    "msgs/echo_req",
    "msgs/echo_start",
    "name_id",
    "echo_start_complete_protocol",
    "echo_requester_protocol",
    "echo_requestee_protocol",
    "msg_local_macro",
    "msg_serde_macro",
    "client",
    "server",
    "incremental_select",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = [ "Wink Saville <wink@saville.com>" ]
