[package]
name = "exper_inter_process_channel"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
manager = { path="manager" }
actor = { path="actor" }
actor_bi_dir_channel = { path="actor_bi_dir_channel" }
actor_thread = { path="actor_thread" }
protocol_set = { path="protocol_set" }
protocol = { path="protocol" }
echo_start_complete_protocol = { path="echo_start_complete_protocol" }
echo_requester_protocol = { path="echo_requester_protocol" }
echo_requestee_protocol = { path="echo_requestee_protocol" }
echo_start = { path="echo_start" }
echo_complete = { path="echo_complete" }
echo_req = { path="echo_req" }
echo_reply = { path="echo_reply" }
msg_header = { path="msg_header" }
msg_serde_json = { path="msg_serde_json" }
msg1 = { path="msg1" }
msg2 = { path="msg2" }
name_id = { path="name_id" }
client = { path="client" }
server = { path="server" }
uuid = "1.2.2"
serde = "1.0.152"
serde_json = "1.0.91"
custom_logger = { git = "https://github.com/winksaville/custom_logger", version = "0.2.0" }
crossbeam-channel = "0.5.6"

[workspace]
members = [
    "manager",
    "actor",
    "actor_bi_dir_channel",
    "actor_thread",
    "protocol_set",
    "protocol",
    "msg_header",
    "msg_serde_json",
    "msg1",
    "msg2",
    "name_id",
    "echo_start_complete_protocol",
    "echo_requester_protocol",
    "echo_requestee_protocol",
    "echo_start",
    "echo_complete",
    "echo_reply",
    "echo_req",
    "msg_local_macro",
    "msg_serde_macro",
    "client",
    "server",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = [ "Wink Saville <wink@saville.com>" ]
