[package]
name = "actor_executor_protocol"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
an_id = { version = "0.1.0", path = "../../an_id" }
req_add_actor = { path = "../../msgs/req_add_actor" }
rsp_add_actor = { path = "../../msgs/rsp_add_actor" }
msg_header = { version = "0.1.0", path = "../../msg_header" }
once_cell = "1.17.1"
protocol = { version = "0.1.0", path = "../../protocol" }
uuid = "1.3.0"
