[package]
name = "cmd_init_issuer_protocol"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
box_msg_any = { version = "0.1.0", path = "../../box_msg_any" }
an_id = { version = "0.1.0", path = "../../an_id" }
cmd_init = { path = "../../msgs/cmd_init" }
msg_header = { version = "0.1.0", path = "../../msg_header" }
once_cell = "1.17.1"
protocol = { version = "0.1.0", path = "../../protocol" }
uuid = "1.3.0"
