[package]
name = "echo_requestee_protocol"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
an_id = { version = "0.1.0", path = "../../an_id" }
echo_rsp = { path = "../../msgs/echo_rsp" }
echo_req = { path = "../../msgs/echo_req" }
msg_header = { version = "0.1.0", path = "../../msg_header" }
once_cell = "1.17.1"
protocol = { version = "0.1.0", path = "../../protocol" }
uuid = "1.3.0"
